apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Prevent Longhorn from auto-creating /var/lib/longhorn disks everywhere.
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      createDefaultDiskLabeledNodes: true
      taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule;node-role.kubernetes.io/master:NoSchedule"
      defaultReplicaCount: 3
    persistence:
      defaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      defaultClassReplicaCount: "3"
      defaultDataLocality: best-effort
      defaultFsType: ext4
      dataEngine: v1
      backupTargetName: ""
    preUpgradeChecker:
      jobEnabled: false          # disable the pre-upgrade hook in GitOps
      upgradeVersionCheck: false # (optional) skip manager-side version gate
