apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ../longhorn/helm-repo.yaml
  - ../longhorn/helmrelease.yaml
  - ../longhorn/storageclasses/longhorn-extra.yaml
  - ../longhorn/storageclasses/local-path-unset-default.yaml
