---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-extra
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  dataEngine: "v1"
  numberOfReplicas: "5"
  dataLocality: "disabled"
  fsType: "ext4"
