apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 77.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
    force: true
  values:
    prometheus:
      service:
        type: LoadBalancer
        port: 9090
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - prometheus.bobshomelab.org
        path: /
        pathType: Prefix
        tls: []
      prometheusSpec:
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn-extra
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    grafana:
      service:
        type: LoadBalancer
        port: 3000
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.bobshomelab.org
        path: /
        pathType: Prefix
        tls: []
    alertmanager:
      service:
        type: LoadBalancer
        port: 9080
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - alertmanager.bobshomelab.org
        path: /
        pathType: Prefix
        tls: []
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn-extra
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
